upgrading to ltp latest
Signed-off-by: Hake Huang <b20222@freescale.com>

diff --git a/testcases/commands/cron/cron02 b/testcases/commands/cron/cron02
--- a/testcases/commands/cron/cron02
+++ b/testcases/commands/cron/cron02
@@ -13,7 +13,7 @@
 #   the GNU General Public License for more details.
 #
 #   You should have received a copy of the GNU General Public License
-#   along with this pronram;  if not, write to the Free Software
+#   along with this program;  if not, write to the Free Software
 #   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 #
 #  FILE   : cron02 
@@ -37,7 +37,7 @@ TEST_USER_HOMEDIR="/home/$TEST_USER"
 
 do_setup(){
 	#erase any data from potential defunt cron test
-	rm -rf /tmp/crontest &> /dev/null
+	rm -rf /tmp/crontest > /dev/null 2>&1
 
     #erase user if he may exist , so we can have a clean env
         rm -rf /home/$TEST_USER
@@ -53,17 +53,15 @@ do_setup(){
         fi
 
 	# restart cron daemon
-# Red Hat uses crond, SuSE/Other uses cron. Check if this is Red Hat/SuSE/Other
-tvar=${MACHTYPE%-*}
-tvar=${tvar#*-}
-echo "Distro type is: $tvar \n"
-
-if [ $tvar != "redhat" -a $tvar != "redhat-linux" ]; then
-
-	/etc/init.d/cron restart
-else
-	/etc/init.d/crond restart
-fi
+	# Red Hat uses crond, SuSE/Other uses cron.
+	if [ -x /etc/init.d/crond ]; then
+		/etc/init.d/crond restart
+	elif [ -x /etc/init.d/cron ]; then
+		/etc/init.d/cron restart
+	else
+		echo "Could not determine cron init.d script."
+		exit 1
+	fi
 }
 
 #-----------------------------------------------------------------------
diff --git a/testcases/kernel/fs/acls/acl_test01 b/testcases/kernel/fs/acls/acl_test01
--- a/testcases/kernel/fs/acls/acl_test01
+++ b/testcases/kernel/fs/acls/acl_test01
@@ -13,7 +13,7 @@
 #   the GNU General Public License for more details.
 #
 #   You should have received a copy of the GNU General Public License
-#   along with this pronram;  if not, write to the Free Software
+#   along with this program;  if not, write to the Free Software
 #   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 #
 #
@@ -24,17 +24,33 @@
 #
 #  HISTORY:
 #    03/03 Jerone Young  (jyoung5@us.ibm.com)
+#    09/08 Jacky Malcles changing the setup to have this TC started by runltp
 #*********************************************************************
-export PATH=$PATH:/usr/sbin/
+#
+################################################################
+#
+# Make sure that uid=root is running this script.
+# Make sure that loop device is built into the kernel
+# Make sure that ACL(Access Control List) and Extended Attribute are
+#     built into the kernel
+#
+#
+################################################################
+
+export TCID=acltest01
+export TST_TOTAL=5
+export TST_COUNT=1
+
+TMP=${TMP:=/tmp}
 
 TEST_USER1="acltest1"
 TEST_USER1_GROUP="users"
 TEST_USER1_PASSWD="ltp_test_pass1"
-#ensure the test partition is ACL aware
-TEST_USER1_HOMEDIR="/tmp/$TEST_USER1"
+TEST_USER1_HOMEDIR="$TMP/tacl/mount-ext3/$TEST_USER1"
 
-FILE_ACL="/tmp/test_file"
-FILE_ACL_LINK="/tmp/test_file_link"
+FILE_ACL="$TMP/tacl/mount-ext3/test_file"
+FILE_ACL_LINK="$TMP/tacl/mount-ext3/test_file_link"
+TCbin=`pwd`
 
 #-----------------------------------------------------------------------
 # FUNCTION:  do_setup
@@ -45,23 +61,20 @@ do_setup(){
 	rm -f $FILE_ACL
 	rm -f $FILE_ACL_LINK
 
-	if [ "$TEST_USER1_HOMEDIR" = "" ]
-	then {
-                echo "Could not find user $TEST_USER1's home directory."
-                exit 1
-        }
-        fi
+	if [ "x$TEST_USER1_HOMEDIR" = "x" ]; then
+		echo "Could not find user $TEST_USER1's home directory."
+		exit 1
+	fi
 
+	# XXX (garrcoop): why is cleanup junk being done in setup??? Bad test!!!
 	rm -rf $TEST_USER1_HOMEDIR 
 	userdel $TEST_USER1 > /dev/null 2>&1
 	sleep 1
-	useradd -d $TEST_USER1_HOMEDIR -m -g $TEST_USER1_GROUP $TEST_USER1 -s /bin/sh
+	useradd -d `pwd`/$TEST_USER1_HOMEDIR -m -g $TEST_USER1_GROUP $TEST_USER1 -s /bin/sh
 
-	if [ $? != 0 ]
-	then {
+	if [ $? -ne 0 ]; then
 		echo "Could not add test user $TEST_USER1."
 		exit 1
-	}
 	fi
 
 }
@@ -71,16 +84,13 @@ do_setup(){
 #-----------------------------------------------------------------------
 
 do_cleanup() {
-	if [ "$TEST_USER1_HOMEDIR" = "" ]
-	then {
-                echo "Could not remove home directory of the user $TEST_USER1."
-                exit 1
-        }
-        fi
-        rm -rf $TEST_USER1_HOMEDIR
-	userdel $TEST_USER1
+	rm -rf $TEST_USER1_HOMEDIR
+	userdel $TEST_USER1 > /dev/null 2>&1
 	rm -f $FILE_ACL > /dev/null 2>&1
 	rm -f $FILE_ACL_LINK > /dev/null 2>&1
+	mount | grep "$TMP/tacl/mount-ext3" && umount -d $TMP/tacl/mount-ext3
+	[ "x$LOOP_DEV" != x ] && losetup -d $LOOP_DEV
+	rm -rf $TMP/tacl
 }
 
 #-----------------------------------------------------------------------
@@ -88,9 +98,78 @@ do_cleanup() {
 #-----------------------------------------------------------------------
 
 iam=`whoami`
-EXIT_CODE=0
 if [ "z$iam" = "z$TEST_USER1" ]
 then
+	echo ""
+else
+	if [ $(id -ru) != 0 ]; then
+		tst_resm TCONF "must be root to execute this script"
+		exit 0
+	fi
+
+	if ! ( test -d $TMP/tacl || mkdir -m 777 $TMP/tacl) ; then
+		tst_resm TCONF "failed to create $TMP/tacl directory."
+		exit 1
+	fi
+
+	trap do_cleanup EXIT
+
+	#	The  following  commands  can  be  used as an example of using
+	#	a loopback device.
+
+	dd if=/dev/zero of=$TMP/tacl/blkext3 bs=1k count=10240 && chmod 777 $TMP/tacl/blkext3
+	if [ $? -ne 0 ] ; then
+		tst_resm TCONF "Failed to create $TMP/tacl/blkext3"
+		exit 0
+	fi
+
+	# Avoid hardcoded loopback device values (-f tries to find the first
+	# available loopback device name)!
+	if ! (LOOP_DEV=$(loop_dev -f) && [ "x$LOOP_DEV" = x ]); then
+		tst_resm TCONF "[ losetup.1 ] Failed to find an available loopback device -- is the required support compiled in your kernel?"
+		exit 0
+	fi
+
+	if ! losetup $LOOP_DEV $TMP/tacl/blkext3 2>&1 > /dev/null; then
+		echo ""
+		tst_resm TCONF "[ losetup.2 ] Failed to setup the device."
+		exit 0
+	fi
+
+	mount | grep ext2
+	if [ $? -ne 0 ]; then
+		mkfs -t ext3 $LOOP_DEV #> /dev/null 2>&1
+		mkdir  -m 777 $TMP/tacl/mount-ext3
+		mount -t ext3 -o defaults,acl,user_xattr $LOOP_DEV $TMP/tacl/mount-ext3
+		if [ $? -ne 0 ]
+		then
+			echo ""
+			tst_resm TCONF "[ mount ] Make sure that ACL (Access Control List)"
+			printf "\t and Extended Attribute are built into the kernel\n"
+			printf "\t Can not mount ext3 file system with acl and user_xattr options\n"
+			exit 1
+		fi
+	else
+
+		mkfs -t ext2 $LOOP_DEV
+		mkdir  -m 777 $TMP/tacl/mount-ext3
+		mount -t ext2 -o defaults,acl,user_xattr $LOOP_DEV $TMP/tacl/mount-ext3
+		if [ $? -ne 0 ]
+		then
+			echo ""
+			tst_resm TCONF "FAILED: [ mount ] Make sure that ACL (Access Control List)"
+			printf "\t and Extended Attribute are built into the kernel\n"
+			printf "\t Can not mount ext2 file system with acl and user_xattr options\n"
+			exit 1
+		fi
+
+	fi
+
+fi
+
+if [ "z$iam" = "z$TEST_USER1" ]
+then
+	echo ""
 	echo "TESTING ACLS FOR 2ND USER $iam"
 
 	#setup files for extended attributes
@@ -99,7 +178,7 @@ then
 
 	echo "Trying extended acls for files"
 	${TCbin}/acl_file_test $FILE_ACL
-	if [ $? != 0 ]
+	if [ $? -ne 0 ]
 	then 
 		EXIT_CODE=1
 		echo "Extended acls for files (FAILED)"
@@ -109,15 +188,16 @@ then
 
 	echo "Trying extended acls for file links"
 	${TCbin}/acl_link_test $FILE_ACL_LINK
-	if [ $? != 0 ]
-        then
-                EXIT_CODE=1
+	if [ $? -ne 0 ]
+	then
+		EXIT_CODE=1
 		echo "Extended acls for links (FAILED)"
 	else 
 		echo "Extended acls for links (PASSED)"	
-        fi
+	fi
 else
 	do_setup
+	echo ""
 	echo "TESTING ACLS FOR USER $iam"
 
 	touch $FILE_ACL
@@ -129,17 +209,17 @@ else
 	
 	echo "Trying extended acls for files"
 	${TCbin}/acl_file_test $FILE_ACL
-	if [ $? != 0 ]
-    	then
-      	 	EXIT_CODE=1
+	if [ $? -ne 0 ]
+	then
+		EXIT_CODE=1
 		echo "Extended acls for files (FAILED)"
 	else
 		echo "Extended acls for files (PASSED)"
-    	fi
+	fi
 
 	echo "Trying extended acls for file links"	
 	${TCbin}/acl_link_test $FILE_ACL_LINK
-	if [ $? != 0 ]
+	if [ $? -ne 0 ]
 	then
 		EXIT_CODE=1
 		echo "Extended acls for links (FAILED)"
@@ -150,13 +230,8 @@ else
 	chown $TEST_USER1 $FILE_ACL
 	chown $TEST_USER1 $FILE_ACL_LINK
 
-	if [ -z ${TCbin} ]
-	then
-   		export TCbin=$PWD
-	fi
-	
-	EXIT_CODE=$?
-	
+	su $TEST_USER1 -c "$0"
+	echo ""
 	do_cleanup
 fi	
 
diff --git a/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile b/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile
--- a/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile
+++ b/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile
@@ -1,53 +1,76 @@
-REDHAT_RELEASE=$(shell rpm -q redhat-release)
-POLICYDEVEL = /usr/share/selinux/devel
-SEMODULE = /usr/sbin/semodule
+#
+#    kernel/security/selinux-testsuite/refpolicy Makefile
+#
+#    Copyright (C) 2009, Cisco Systems Inc.
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+# Garrett Cooper, January 2010
+#
 
-TARGETS=test_global.te test_bounds.te test_capable_file.te test_capable_net.te \
-test_capable_sys.te test_dyntrace.te test_dyntrans.te test_entrypoint.te \
-test_execshare.te test_exectrace.te test_execute_no_trans.te \
-test_fdreceive.te test_file.te test_inherit.te test_ioctl.te test_ipc.te \
-test_link.te test_mkdir.te test_open.te test_ptrace.te test_readlink.te \
-test_relabel.te test_rename.te test_rxdir.te test_setattr.te test_setnice.te \
-test_sigkill.te test_stat.te test_sysctl.te test_task_create.te \
-test_task_getpgid.te test_task_getsched.te test_task_getsid.te \
-test_task_setpgid.te test_task_setsched.te test_transition.te test_wait.te 
+top_srcdir		?= ../../../../..
 
-ifeq (redhat-release-4, $(findstring redhat-release-4, $(REDHAT_RELEASE)))
-    TARGETS=test_global.te test_capable_file.te test_capable_net.te \
-    test_capable_sys.te test_entrypoint.te \
-    test_execshare.te test_exectrace.te test_execute_no_trans.te \
-    test_fdreceive.te test_file.te test_inherit.te test_ioctl.te test_ipc.te \
-    test_link.te test_mkdir.te test_open.te test_ptrace.te test_readlink.te \
-    test_relabel.te test_rename.te test_rxdir.te test_setattr.te test_setnice.te \
-    test_sigkill.te test_stat.te test_sysctl.te test_task_create.te \
-    test_task_getpgid.te test_task_getsched.te test_task_getsid.te \
-    test_task_setpgid.te test_task_setsched.te test_transition.te test_wait.te 
+include	$(top_srcdir)/include/mk/env_pre.mk
+
+ARGS			= -m
+# Don't want to pass the -d option unless DESTDIR is a non-zero length string.
+ifneq ($(strip $(DESTDIR)),)
+ARGS			+= -d $(DESTDIR)
 endif
 
-ifeq (redhat-release-5, $(findstring redhat-release-5, $(REDHAT_RELEASE)))
-    TARGETS=test_global.te test_capable_file.te test_capable_net.te \
-    test_capable_sys.te test_dyntrace.te test_dyntrans.te test_entrypoint.te \
-    test_execshare.te test_exectrace.te test_execute_no_trans.te \
-    test_fdreceive.te test_file.te test_inherit.te test_ioctl.te test_ipc.te \
-    test_link.te test_mkdir.te test_open.te test_ptrace.te test_readlink.te \
-    test_relabel.te test_rename.te test_rxdir.te test_setattr.te test_setnice.te \
-    test_sigkill.te test_stat.te test_sysctl.te test_task_create.te \
-    test_task_getpgid.te test_task_getsched.te test_task_getsid.te \
-    test_task_setpgid.te test_task_setsched.te test_transition.te test_wait.te 
+DISTRO_VER		:= $(shell $(top_srcdir)/scripts/detect_distro.sh $(ARGS))
+
+# Avoid empty strings.
+ifeq ($(strip $(DISTRO_VER)),)
+DISTRO_VER		:= generic
 endif
 
-load:
-	@if [ -d $(POLICYDEVEL) ]; then \
-		set -e; rm -f test_policy.te; for i in $(TARGETS); do cat $$i >> test_policy.te; done; \
-		cp test_policy.* $(POLICYDEVEL); \
-		$(MAKE) -C $(POLICYDEVEL) clean test_policy.pp; \
-		$(SEMODULE) -i $(POLICYDEVEL)/test_policy.pp; \
+CHECKPOLICY		?= $(DESTDIR)/usr/bin/checkpolicy
+CHECKPOLICY_VERS	?= $(shell $(CHECKPOLICY) -V |cut -f 1 -d ' ')
+POLICY_DEVEL_DIR	?= $(DESTDIR)/usr/share/selinux/devel
+
+INSTALL_DIR		:= testcases/kernel/security/selinux-testsuite/refpolicy
+
+TEST_POLICY_DIR		:= $(abs_srcdir)/policy_files
+
+# Do we have a special set of policies in the SCM to install?
+ifneq ($(wildcard $(TEST_POLICY_DIR)/$(DISTRO_VER)/),)
+TEST_POLICY_DIR		:= $(TEST_POLICY_DIR)/$(DISTRO_VER)
+else
+TEST_POLICY_DIR		:= $(TEST_POLICY_DIR)/generic
+endif
+
+MAKE_TARGETS		:= test_policy.te test_policy.pp
+
+# This is being done to preserve precedence; test_global.te must come first.
+POLICY_FILES		:= test_global.te \
+			   $(filter-out test_global.te,$(notdir $(wildcard $(TEST_POLICY_DIR)/*.te)))
+
+ifneq ($(CHECKPOLICY_VERS),24)
+POLICY_FILES		:= $(filter-out test_bounds.te,$(POLICY_FILES))
+endif
+
+test_policy.te: $(addprefix $(TEST_POLICY_DIR)/,$(POLICY_FILES))
+	(cd "$(TEST_POLICY_DIR)" && cat $(POLICY_FILES)) > $@
+
+test_policy.pp: test_policy.te
+	set -e; if [ -d "$(POLICY_DEVEL_DIR)" ]; then \
+		$(MAKE) -f $(POLICY_DEVEL_DIR)/Makefile test_policy.pp; \
 	else \
-		echo "ERROR: You must have selinux-policy-devel installed."; \
+		echo "ERROR: You must have selinux-policy?-devel? installed."; \
+		false; \
 	fi
-	
-cleanup:
-	$(SEMODULE) -r test_policy
-	rm -f $(POLICYDEVEL)/test_policy.* 
-	rm -f test_policy.te 
 
+include $(top_srcdir)/include/mk/generic_leaf_target.mk
